import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import { Questrial } from "next/font/google";
import Navbar from "@/components/main-store-components/navbar";
import { ThemeProvider } from "@/providers/theme-provider";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
const questrial = Questrial({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "font-sans text-foreground",
          questrial.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
